# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'examples/**/*'
    # - 'tmp/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/WhileUntilModifier:
  MaxLineLength: 120

Metrics/LineLength:
  Max: 120

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Style/IndentArray:
#   EnforcedStyle: align_brackets
